### simulacao produto Produto 1
POST http://localhost:8080/api/simulacoes
Content-Type: application/json

{
  "valorDesejado": 9000.00,
  "prazo": 20
}

### simulacao produto  2
POST http://localhost:8080/api/simulacoes
Content-Type: application/json

{
  "valorDesejado": 50000.00,
  "prazo": 36
}

### simulacao produto  3
POST http://localhost:8080/api/simulacoes
Content-Type: application/json

{
"valorDesejado": 150000.00,
"prazo": 60
}

### simulacao produto 4
POST http://localhost:8080/api/simulacoes
Content-Type: application/json

{
"valorDesejado": 1200000.00,
"prazo": 120
}

### simulacao parametros invalidos
POST http://localhost:8080/api/simulacoes
Content-Type: application/json

{
  "valorDesejado": 100.00,
  "prazo": 5
}

### listas simulacoes
GET http://localhost:8080/api/simulacoes?page=0&size=10
Accept: application/json

### volume diario
GET http://localhost:8080/api/simulacoes/volume-diario?data=2025-08-21
Accept: application/json

### dados de telemetria
GET http://localhost:8080/api/telemetria
Accept: application/json